# Берем node.js v8 в качестве родительского образа
FROM node:8-alpine
#RUN apt-get update && apt-get install sudo -y
# Устанавливаем рабочую директорию
WORKDIR /app
# Копируем файлы yarn.lock и package.json в рабочую директорию
COPY package.json package-lock.json /app/
# Устанавливаем зависимости
RUN npm install
# Открываем порт 3000
EXPOSE 3000
# Запускаем React-приложение после запуска контейнера
CMD ["npm", "start"]