import React from 'react';
import './about.scss';

const About= () => {
    return (
        <div>
            ABOUT PAGE!

            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            This is about page with a very big text. This is about page with a very big text. 
            
        </div>
    )
}

export default About;